### ISSUE TITLE
安装后执行hexo g时报错

### ISSUE THREAD

**Issue by batteryhp** [henryhuang/hexo-theme-aloha#12]
我安装好aloha主题后，执行`hexo g` 命令，出现下面错误
```
INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
INFO  [hexo-math] Using engine 'mathjax'
INFO  Start processing
INFO  Files loaded in 302 ms
Unhandled rejection Error: H:\hexo\themes\aloha\layout\post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

H:\hexo\themes\aloha\layout\_partial\article.ejs:61
    59|                 <div class="ui sticky article-toc" id="article-toc">
    60|                     <!-- toc -->
 >> 61|                     <%- toc_semantic(page.content) %>
    62|                 </div>
    63|
    64|             </div>

Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.tocHelper (H:\hexo\themes\aloha\scripts\helper\toc.js:7:29)
    at Object.wrapper [as toc_semantic] (H:\hexo\node_modules\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:46:2162)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:54:52)
    at H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (H:\hexo\node_modules\hexo-inject\lib\patch\view.js:31:22)
    at View.renderSync (H:\hexo\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (H:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (H:\hexo\node_modules\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:101)
    at H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (H:\hexo\node_modules\hexo-inject\lib\patch\view.js:38:43)
    at View.render (H:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at H:\hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (H:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at H:\hexo\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (H:\hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:328:10)
    at resume_ (_stream_readable.js:718:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Unhandled rejection Error: H:\hexo\themes\aloha\layout\post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

H:\hexo\themes\aloha\layout\_partial\article.ejs:61
    59|                 <div class="ui sticky article-toc" id="article-toc">
    60|                     <!-- toc -->
 >> 61|                     <%- toc_semantic(page.content) %>
    62|                 </div>
    63|
    64|             </div>

Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.tocHelper (H:\hexo\themes\aloha\scripts\helper\toc.js:7:29)
    at Object.wrapper [as toc_semantic] (H:\hexo\node_modules\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:46:2162)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:54:52)
    at H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (H:\hexo\node_modules\hexo-inject\lib\patch\view.js:31:22)
    at View.renderSync (H:\hexo\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (H:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (H:\hexo\node_modules\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:101)
    at H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (H:\hexo\node_modules\hexo-inject\lib\patch\view.js:38:43)
    at View.render (H:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at H:\hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (H:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at H:\hexo\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (H:\hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:328:10)
    at resume_ (_stream_readable.js:718:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Unhandled rejection Error: H:\hexo\themes\aloha\layout\post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

H:\hexo\themes\aloha\layout\_partial\article.ejs:61
    59|                 <div class="ui sticky article-toc" id="article-toc">
    60|                     <!-- toc -->
 >> 61|                     <%- toc_semantic(page.content) %>
    62|                 </div>
    63|
    64|             </div>

Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.tocHelper (H:\hexo\themes\aloha\scripts\helper\toc.js:7:29)
    at Object.wrapper [as toc_semantic] (H:\hexo\node_modules\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:46:2162)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:54:52)
    at H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (H:\hexo\node_modules\hexo-inject\lib\patch\view.js:31:22)
    at View.renderSync (H:\hexo\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (H:\hexo\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (H:\hexo\node_modules\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:101)
    at H:\hexo\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (H:\hexo\node_modules\hexo-inject\lib\patch\view.js:38:43)
    at View.render (H:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at H:\hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (H:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at H:\hexo\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (H:\hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:328:10)
    at resume_ (_stream_readable.js:718:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
INFO  Generated: css/aloha.less
INFO  Generated: images/algolia_logo.svg
INFO  Generated: images/scrolltop.png
INFO  Generated: css/semantic-ui/2.2.4/themes/default/assets/fonts/icons.eot
INFO  Generated: css/semantic-ui/2.2.4/themes/default/assets/fonts/icons.woff2
INFO  Generated: favicon.ico
INFO  Generated: css/semantic-ui/2.2.4/themes/default/assets/fonts/icons.ttf
INFO  Generated: css/semantic-ui/2.2.4/themes/default/assets/fonts/icons.woff
INFO  Generated: css/aloha.css
INFO  Generated: js/aloha.js
INFO  Generated: js/aloha-events.js
INFO  Generated: js/semantic-ui-algolia.js
INFO  Generated: css/semantic-ui/2.2.4/semantic.min.css
INFO  Generated: archives/index.html
INFO  Generated: archives/2017/03/index.html
INFO  Generated: archives/2017/index.html
INFO  Generated: index.html
INFO  Generated: images/avatar.jpg
INFO  Generated: css/semantic-ui/2.2.4/themes/default/assets/fonts/icons.svg
```  
前面我用的是默认的`landscape`主题，并且已经写过在_post文件夹下有几个`md`文件。这种错误的原因是什么？

**Comment by batteryhp** [comment]
执行 `npm install cheerio` 安装 `cheerio` 即可，关闭。

**Comment by henryhuang** [comment]
@batteryhp 可能是你原来hexo版本生成的项目没有cheerio吧。
